---
# zabbix-proxy導入
- name: zabbix-repo_add
  yum:
    name: http://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: zabbix-proxy_install
  shell: "yum install zabbix-proxy-sqlite3 sqlite-3.26.0-15.el8.x86_64 --disablerepo=epel-modular -y"

- name: create sqlite3 dir
  file:
    path: /var/lib/sqlite3
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0755

- name: confirm zabbix.db
  stat:
    path: /var/lib/sqlite3/zabbix.db
  register: result_zabbixdb

- name: deploy db data
  shell: zcat /usr/share/doc/zabbix-proxy-sqlite3/schema.sql.gz | /bin/sqlite3 zabbix.db
    chdir=/var/lib/sqlite3/
  when: not result_zabbixdb.stat.exists

- name: chown zabbix.db
  shell: chown zabbix:zabbix zabbix.db
    chdir=/var/lib/sqlite3/

- name: zabbix-proxy.conf change
  lineinfile:
    dest: "/etc/zabbix/zabbix_proxy.conf"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "Server=127.0.0.1" ,line: "Server={{ zabbix_server_ip | default('127.0.0.1', true) }}" }
    - { regexp: "DBName=zabbix_proxy" ,line: "DBName=/var/lib/sqlite3/zabbix.db" }
    - { regexp: "Hostname=Zabbix proxy" ,line:  "Hostname={{ inventory_hostname }}" }

#サービスの起動
  notify: zabbix-proxy_start 
